### ISSUE TITLE
add me to the group

### ISSUE THREAD

**Issue by netadavani-06** [Jay-study-nildana/FrontEndForStudents#13]
Hello sir.......can you please add me to the batch " Edureka7PMMentorshipBatchPrivate"

**Comment by mozes2019** [comment]
Hello Mr Jay.
Could you please provide me the sequence of command to reach the calculator project code error that you fixed. My repository is mozes2019/laravel11cjh. I sent you request couple months ago but no feedback yet. I can access your Github where issues supposed to be fixed (https://github.com/Jay-study-nildana/FrontEndForStudents/issues/) through my Github (mozes2019/laravel11cjh) but no way to see the calculator code error fixed.

Best regards

Cece Jules HABA, Student in PhD AIML major academic program, AIU
