### ISSUE TITLE
Unable to configure Git on PC

### ISSUE THREAD

**Issue by ananya-2023** [Jay-study-nildana/FrontEndForStudents#32]
### Discussed in https://github.com/Jay-study-nildana/FrontEndForStudents/discussions/31

<div type='discussions-op-text'>

<sup>Originally posted by **ananya-2023** June 17, 2023</sup>
Good Evng, 

As you have mentioned earlier, even after authenticating /logging in, cloning is failing everytime. could you kindly help: 

SMRUTI@SMRUTI-PC MINGW64 ~/Videos/Edureka
$ git clone https://github.com/ananya-2023/practicemarch052023.git
Cloning into 'practicemarch052023'...
fatal: An error occurred while sending the request.
fatal: The request was aborted: Could not create SSL/TLS secure channel.
error: unable to read askpass response from 'C:/Program Files/Git/mingw64/bin/git-askpass.exe'
Username for 'https://github.com': ananya-2023
Smayan!2016
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/ananya-2023/practicemarch052023.git/'

SMRUTI@SMRUTI-PC MINGW64 ~/Videos/Edureka
$ Smayan!2016
bash: !2016: event not found

SMRUTI@SMRUTI-PC MINGW64 ~/Videos/Edureka
$ git clone https://github.com/ananya-2023/practicemar2023.git
Cloning into 'practicemar2023'...
fatal: unable to access 'https://github.com/ananya-2023/practicemar2023.git/': Failed to connect to github.com port 443 after 21676 ms: Couldn't connect to server

SMRUTI@SMRUTI-PC MINGW64 ~/Videos/Edureka
$ git clone https://github.com/ananya-2023/practicemar2023.git
Cloning into 'practicemar2023'...
fatal: An error occurred while sending the request.
fatal: The request was aborted: Could not create SSL/TLS secure channel.

unable to troubleshoot or move forward. 
</div>

**Comment by Jay-study-nildana** [comment]
This is a duplicate issue. I have given reply in the main discussion. 

https://github.com/Jay-study-nildana/FrontEndForStudents/discussions/31

Closing this. Please continue in the other discussion @ananya-2023 

Thank you

Jay

**Comment by Jay-study-nildana** [comment]
and don't forget to follow me on socials (links are available on my github profile) and stay in touch. Happy  learning.

Jay
