### ISSUE TITLE
javascript problem

### ISSUE THREAD

**Issue by mohammedawez** [Jay-study-nildana/FrontEndForStudents#42]
hlo jay sir..!!!

@Jay-study-nildana 

how are You ,hope everithing is good ,and i think new business is comming up soon

As you know i m learning somthing new , so i have some errror's in my code ,can u plz solve it ,and provide me what mistake i have Done

file repository :- https://github.com/mohammedawez/javascript-problem-2-api-

 clone clone   :- https://github.com/mohammedawez/javascript-problem-2-api-.git

@Jay-study-nildana

**Comment by Jay-study-nildana** [comment]
@mohammedawez 

I am traveling on holiday to Pondicherry, my friend. I will be gone for 10 to 20 days. Unable to help right now.

But, you can read about my traveling on my blog. 

https://vijayasimhabr.medium.com/list/jays-traveling-logs-9175beaccfc4

Thanks
Jay.

**Comment by mohammedawez** [comment]
@Jay-study-nildana 


It's k👍 sir,No problem ...!   thank you
