### ISSUE TITLE
Hello sir, this is jyoti from edureka batch nov 24.

### ISSUE THREAD

**Issue by Jay-study-nildana** [Jay-study-nildana/FrontEndForStudents#47]
@Jay-study-nildana 
Hello sir, this is jyoti from edureka batch nov 24.

_Originally posted by @jyotimane2705 in https://github.com/Jay-study-nildana/TutoringTrainingStudents/discussions/93#discussioncomment-8280814_

**Comment by Jay-study-nildana** [comment]
@jyotimane2705

Hello. Good to have you here. 

I have made some beginner tutorials. See if they will help you.   

https://youtube.com/playlist?list=PL7SHzFbuSdW0OLny_GyfMxLKidxeurrPz&si=SW7BeDVxnaJKjn07  

If you still have questions, post them on my student coding forum.  

https://github.com/Jay-study-nildana/FrontEndForStudents/discussions  all the best :) 

If you are based in Bangalore, I am always looking for interns, and you can contact me using the details on my company website, [amiay.in ](http://amiay.in)

All the best. 

Jay (Vijayasimha BR)

**Comment by jyotimane2705** [comment]
@Jay-study-nildana 
Really liked your videos, and following you ,
Thank you for explaining things where I can easily understand them.
Jyoti

**Comment by Jay-study-nildana** [comment]
@jyotimane2705 

Excellent. Very excellent. Thank you for your kind words. 

Jay.

**Comment by jyotimane2705** [comment]
@Jay-study-nildana 

Succefully commited files and uploading files on Git Hub.
Thanks to you Jay sir.

Jyoti.

**Comment by Jay-study-nildana** [comment]
@jyotimane2705 

Excellent. Feel free to continue updating me as you do more things, and you have any doubts, you are always welcome to ask. 

Thank you.

Jay (Vijayasimha BR)
