### ISSUE TITLE
having a question regarding practicing coding

### ISSUE THREAD

**Issue by VarshaKATE** [Jay-study-nildana/FrontEndForStudents#49]
hello, 
Jay sir.

sir my question is everyone says practice the code but how to do it i mean i should take a reference from w3school, freecodecamp, and copy there code, and understand or i have to do it by myself as a biginer there are so many thing which are quite difficult to understand and trying hard, so plz tell me how should i practice so i will be good at frontend. plz guide me. and i also want small small FE project so i will take a look in that will try to understand and implement.

**Comment by Jay-study-nildana** [comment]
Varsha,

So, If you are completely new to coding, then, you have to understand that it will take at least 12 months to 18 months to become developer. Assuming, you are practicing at least 10 hours every week. 

Now, you have to use one website, and focus on that, till you finish it. For example, if you start learning with w3 school, then, you have to focus only on that, and finish it. After that, you start with with freecodecamp, and finish it. 

So, like this, you start one by one, and start finishing the topics. As usual, please check this link, 

1. https://github.com/Jay-study-nildana/FrontEndForStudents 

and any questions, feel free to put them here. Remember, Patience and Virtue is what really makes you a developer. 

Jay (Vijayasimha BR)

**Comment by VarshaKATE** [comment]
For front end I have to learn html css bootstrap javascript and angular or
react??

**Comment by Jay-study-nildana** [comment]
Varsha

1. For front end, you have to begin with HTML and CSS. This will take roughly 30 to 60 days of learning. (assuming 10 hours per week).
3. Then, you should spend some time with Bootstrap. This will be around 10 days of learning. 
4. Then, you should spend time with JavaScript (60 to 120 days of learning). 

Here are some links that will help you. 

1. https://github.com/Jay-study-nildana/somecoolrepos
2. https://github.com/Jay-study-nildana/FrontEndForStudents/tree/main/HTMLCSSForStudents
3. https://github.com/Jay-study-nildana/FrontEndForStudents/tree/main/BootstrapForStudents
4. https://github.com/Jay-study-nildana/FrontEndForStudents/tree/main/JSForStudents

Only after these things are over, you can decide which 'front end framework', you have to choose. Here are some options for front end framework. 

**Important Note: If you try to learn these frameworks without first spending 2 to 4 months learning the above basics of HTML, CSS, JAVASCRIPT AND BOOTSTRAP, then, it will give you a nice headache and you will not learn anything :)** 

1. React JS (my personal recommendation) (60 days to 120 days of learning)
5. Angular JS (I hate it, but, many people like it)
6. Vue JS (I don't hate it or recommend it, but, many people use this)

Thank you. 

Jay (Vijayasimha BR)

**Comment by VarshaKATE** [comment]
Thank you sir ☺️ for the information.
